### ISSUE TITLE
[Question]: Blindness after damage

### ISSUE THREAD

**Issue by Parker8396** [AllTheMods/Spellbound#75] opened 2022-01-10 22:40 UTC
### What would you like to know?

After last update, on my server any time we take damage, it gives us the blindness status. Anyway to disable?

**Comment by gxam** [comment] 2022-01-11 02:23
This is a bug with one of the new mods added in 2.2.2.

**Comment by Mr-Brainiac237** [comment] 2022-01-11 18:51
I'm having the same issue with this bug. I did some testing in a new world and it seems that it's suppose to be the bleeding effect from Mahou Tsukai but instead its giving the blindness effect. Very odd that it only is effecting worlds that were updated.

**Comment by stepsword** [comment] 2022-01-11 20:04
yea its caused by vanilla potion ids, if mahou gets added to an existing spellbound world it gets assigned ids over 255 (cause all the id's below 255 are taken - but on new worlds mahou gets potion ids below 255 cause they go alphabetically on new worlds). when vanilla sends packets to the client about it, it messes up if the ID is above 255. 

here is a mod to remove the limitation: https://www.curseforge.com/minecraft/mc-mods/potion-id-packet-fixer

**Comment by ClockwiseGear** [comment] 2022-01-13 05:47
Same issue here as well. Will try adding the mod stepsword suggests

**Comment by ZephyrWindSpirit** [comment] 2022-01-16 22:27
https://www.curseforge.com/minecraft/mc-mods/potion-id-packet-fixer
Install this. problem solved. 
Or wait on a fix.

**Comment by Mitchell5200** [comment] 2022-11-03 08:36
Potion ID fixer added to modpack, Confirmed fixed in V2.2.7, Closing

**Closed by Mitchell5200** 2022-11-03 08:36 UTC
Labels: Question
