### ISSUE TITLE
Cant make conjure water in ars nouveau quest log.

### ISSUE THREAD

**Issue by BreazyLantern** [AllTheMods/Spellbound#55] opened 2021-12-07 03:32 UTC
There is a quest to make all the spells in ars nouveau and I can't complete it because I can't make conjure water.

**Comment by gxam** [comment] 2022-01-14 20:17
This works for me in 2.2.2.  Marvelous clay + bucket of water.  If it is still not working for you we'll need more information to debug.  What version you're on and what exactly you tried to make it.

**Comment by BreazyLantern** [comment] 2022-01-17 15:52
I think this issue was patched a from one of your updates to the modpack.

**Comment by Mitchell5200** [comment] 2022-11-03 06:17
Confirmed fixed in V2.2.7, Closing

**Closed by Mitchell5200** 2022-11-03 06:17 UTC
